Change arguments order * before: marlin <DEVICE> <OPERATION> * after:  marlin <OPERATION> <DEVICE>

diff --git a/bin/marlin b/bin/marlin
--- a/bin/marlin
+++ b/bin/marlin
@@ -50,7 +50,7 @@ function main() {
       echo "Unknown command: ${argv[1]}" >&2
       exit 1
     fi
-  elif [[ "${argv[1]}" = "register" ]]; then
+  elif [[ "${argv[0]}" = "register" ]]; then
     register
   else
     operate
@@ -64,19 +64,27 @@ function list() {
 
 
 function operate() {
-  target_extract=$(echo -e "${adapters[@]}" | bluetoothctl | grep -E "^Device " -B 2 | grep -i -E "^Device ([0-9A-F]{2}:){5}[0-9A-F]{2} ${argv[0]}" -B 2)
+  if [[ "${argv[1]}" = "" ]]; then
+    echo "Device is missing" >&2
+    exit 1
+  fi
+
+  target_extract=$(echo -e "${adapters[@]}" | bluetoothctl | grep -E "^Device " -B 2 | grep -i -E "^Device ([0-9A-F]{2}:){5}[0-9A-F]{2} ${argv[1]}" -B 2)
 
   if [[ "${target_extract}" = "" ]]; then
-    echo "No such device: ${argv[0]}" >&2
+    echo "No such device registered: ${argv[1]}" >&2
+    echo
+    echo "The following command might help you" >&2
+    echo "$PROGNAME register ${argv[1]}" >&2
     exit 2
   fi
 
   device=$(echo "${target_extract}" | grep "Device " | awk '{print $2}')
   adapter=$(echo "${target_extract}" | grep -oE -e "Controller ([0-9A-F]{2}:){5}[0-9A-F]{2}" -e "select ([0-9A-F]{2}:){5}[0-9A-F]{2}" | awk '{print $2}')
 
-  if [[ "${argv[1]}" = "" ]] || [[ "${argv[1]}" = "info" ]]; then
+  if [[ "${argv[0]}" = "info" ]] || [[ "${argv[0]}" = "status" ]]; then
     echo -e "select ${adapter}\n\ninfo ${device}\n\n" | bluetoothctl | grep -e "Name: " -e "Paired: " -e "Trusted: " -e "Blocked: " -e "Connected: " | sed "s/^[ \t]*//"
-  elif [[ "${argv[1]}" = "remove" ]]; then
+  elif [[ "${argv[0]}" = "remove" ]]; then
     {
       printf "select ${adapter}\n\n"
       sleep $INTERVAL_AFTER_SELECT
@@ -96,7 +104,7 @@ function operate() {
       sleep $INTERVAL_AFTER_SELECT
       printf "power on\n\n"
       sleep $INTERVAL_AFTER_POWER_ON
-      printf "${argv[1]} ${device}\n\n"
+      printf "${argv[0]} ${device}\n\n"
       sleep $INTERVAL_AFTER_ANY_OTHER_COMMAND
       printf "exit\n\n"
     } | bluetoothctl
@@ -109,15 +117,15 @@ function register() {
     touch ~/.marlin_aliases
   fi
 
-  device_hit_count=$(cat ~/.marlin_aliases | grep -c -i "${argv[0]}")
+  device_hit_count=$(cat ~/.marlin_aliases | grep -c -i "${argv[1]}")
 
   if [[ "$device_hit_count" -eq 0 ]]; then
-    echo -e "No such device: ${argv[0]}\n" >&2
+    echo -e "No such device: ${argv[1]}\n" >&2
     echo "Hint: use ~/.marlin_aliases like this" >&2
     echo "echo \"<YOUR_DEVICE_BD_ADDRESS> <YOUR_DEVICE_NAME>\" >> ~/.marlin_aliases" >&2
     exit 2
   elif [[ "$device_hit_count" -ge 2 ]]; then
-    echo "Too many devices hit by word \"${argv[0]}\"" >&2
+    echo "Too many devices hit by word \"${argv[1]}\"" >&2
     exit 2
   fi
 
@@ -138,7 +146,7 @@ function register() {
     exit 2
   fi
 
-  device=$(cat ~/.marlin_aliases | grep -i "${argv[0]}" | grep -o -E "([0-9A-F]{2}:){5}[0-9A-F]{2}")
+  device=$(cat ~/.marlin_aliases | grep -i "${argv[1]}" | grep -o -E "([0-9A-F]{2}:){5}[0-9A-F]{2}")
 
   {
     printf "select $not_paired_adapter\n\n"
@@ -178,12 +186,11 @@ function paired_devices() {
 
 
 function usage() {
-  echo -e "Usage: $PROGNAME [-h]"
+  echo -e "Usage: $PROGNAME -h|--help"
   printf  "       %${#PROGNAME}s [list]\n"
   printf  "       %${#PROGNAME}s list [diff]\n"
   printf  "       %${#PROGNAME}s alias [edit]\n"
-  printf  "       %${#PROGNAME}s DEVICE_NAME|DEVICE_BD_ADDRESS [info]\n"
-  printf  "       %${#PROGNAME}s DEVICE_NAME|DEVICE_BD_ADDRESS [register|ANY_OTHER_BLUETOOTHCTL_COMMAND]\n"
+  printf  "       %${#PROGNAME}s info|status|register|BLUETOOTHCTL_COMMAND DEVICE_NAME|DEVICE_BD_ADDRESS\n"
   echo
   echo
   echo -e "Description:"
@@ -206,19 +213,18 @@ function usage() {
   echo -e "	alias edit"
   echo -e "		Edit ~/.marlin_aliases with your environment's default editor"
   echo
-  echo -e "	DEVICE_NAME|DEVICE_BD_ADDRESS [info]"
+  echo -e "	info|status DEVICE_NAME|DEVICE_BD_ADDRESS"
   echo -e "		Show specified device's information"
-  echo -e "		\"info\" can be omittable"
-  echo -e "		e.g. \"$PROGNAME macbook info\""
   echo
-  echo -e "	DEVICE_NAME|DEVICE_BD_ADDRESS register"
+  echo -e "	register DEVICE_NAME|DEVICE_BD_ADDRESS"
   echo -e "		Pair, trust, and connect a specified device"
   echo -e "		It attempts to pair the device forever unless it is not paired"
-  echo -e "		e.g. \"$PROGNAME macbook register\""
   echo
-  echo -e "	DEVICE_NAME|DEVICE_BD_ADDRESS ANY_OTHER_BLUETOOTHCTL_COMMAND"
-  echo -e "		Operate any bluetoothctl command to a specified device, like \"remove\""
-  echo -e "		e.g. \"$PROGNAME macbook remove\""
+  echo -e "	BLUETOOTHCTL_COMMAND DEVICE_NAME|DEVICE_BD_ADDRESS"
+  echo -e "		Operate any bluetoothctl command to a specified device"
+  echo -e "		e.g. \"$PROGNAME connect macbook\""
+  echo -e "		     \"$PROGNAME disconnect macbook\""
+  echo -e "		     \"$PROGNAME remove macbook\""
   echo
   echo
   echo -e "Tips:"
