Fix always show "No paired devices found" in list function

diff --git a/bin/marlin b/bin/marlin
--- a/bin/marlin
+++ b/bin/marlin
@@ -63,12 +63,22 @@ function main() {
       exit 1
     fi
   elif [[ "$subcommand" = "register" ]]; then
+    if [[ "${argv[0]}" = "" ]]; then
+      echo "Device is missing" >&2
+      exit 1
+    fi
+
     while [[ "${argv[0]}" != "" ]]; do
       register
       argv=( "${argv[@]:1}" )
       echo
     done
   else
+    if [[ "${argv[0]}" = "" ]]; then
+      echo "Device is missing" >&2
+      exit 1
+    fi
+
     while [[ "${argv[0]}" != "" ]]; do
       operate
       argv=( "${argv[@]:1}" )
@@ -79,7 +89,13 @@ function main() {
 
 
 function list() {
-  (echo -e ${adapters_cmd[@]} | bluetoothctl | grep "Device " | sed -e "s/^Device //" | sort) | (echo "No paired devices found" >&2)
+  paired_devices=$(echo -e ${adapters_cmd[@]} | bluetoothctl | grep "Device " | sed -e "s/^Device //" | sort)
+
+  if [[ "${paired_devices}" != "" ]]; then
+    echo "${paired_devices}"
+  else
+    echo "No paired devices found" >&2
+  fi
 }
 
 
@@ -89,11 +105,6 @@ function alias() {
 
 
 function operate() {
-  if [[ "${argv[0]}" = "" ]]; then
-    echo "Device is missing" >&2
-    exit 1
-  fi
-
   target_extract=$(echo -e "${adapters_cmd[@]}" | bluetoothctl | grep -E "^Device " -B 2 | grep -i -E "^Device ([0-9A-F]{2}:){5}[0-9A-F]{2} ${argv[0]}" -B 2)
 
   if [[ "${target_extract}" = "" ]]; then
